<img src="./imagenes/logo_UTN.svg" align="right" width="200"/>

# **Electronica Aplicada II**
## Trabajo práctico de laboratorio N°1


---
**Profesor:** Ing. Eduardo Marchionni \
**Ayudantes:** Ing. Kevin Wojtyszyn, Ing.Dario Nonino\

**Alumnos:** Nicolas Gaston Del Campo, Camila Maria De Uriarte, Matias Boroski, Valentin Dorrego\
**Curso:** R4053\
**Ciclo lectivo:** 2026  

---

## **Objetivos del trabajo**

El objetivo principal del trabajo es poder verificar los contenidos teóricos vistos en la materia, para
cumplir con ese fin se propone ensayar circuitos con amplificadores operacionales como lo pueden ser
amplificadores inversores, no inversores, derivadores e integradores con diversas señales de entrada.
Algunos de los parámetros a verificar son:

- Errores estáticos en amplificadores operacionales
- Respuesta en frecuencia a lazo cerrado.
- Análisis de estabilidad.
- Frecuencia de corte superior.
- Respuesta temporal a la señal escalón.
- Respuesta temporal a señales senoidales, triangulares y cuadradas.
- Slew Rate


## Corrección de errores estáticos: Corriente de polarización y offset de tensión

En esta primera sección se busca simular los errores estáticos del amplificador operacional y la
configuración como derivador estudiándolo desde un análisis de realimentación.
Para analizar los problemas estáticos del amplificador operacional se propone utilizar el CI LM741, una
alimentación simétrica de ±12V y una resistencia de carga de 10K.
Se deben simular las siguientes configuraciones, analizando cómo varía la tensión de offset modificando
el valor de R en el terminal no inversor, para distintos valores de Rs y Rf.

- Rs=10 - Rf=1K
- Rs=100 - Rf=10K
- Rs=1K - Rf=100K
- Rs=10K - Rf=1000K
  
<div align="center">
  <img src="imagenes/1/ilustracion1.png" width="400">
  <figcaption>Ilustración 1 Configuración inversora con fuente de señal pasivada.</figcaption>
</div>

- Obtener conclusiones respecto a la corriente a la salida del operacional para cada par de valores de
Rs - Rf. Analizar la corriente de salida que debe entregar el operacional en cada caso.
- ¿Es posible utilizar cualquier configuración con valor de R=0? ¿Cuál es la función de dicha resistencia?
- Repetir el procedimiento anterior con valores de resistencias Rs=10K - Rf=1000K – R=0 utilizando el
operacional LT1012. Comparar los resultados con el LM741 en la misma configuración. ¿Cuál es la
razón por la que varía el offset de salida?

### Análisis
En primera intancia comenzamos con la simulacion con el integrado LM741

<div align="center">
  <img src="imagenes/1/ilustracion2.png" width="600">
  <figcaption>Ilustración 2 Circuito en LTSpice.</figcaption>
</div>

para facilitar el analisis del circuito, utilizamos este [script](https://github.com/ValentinDorrego/eaII/blob/main/TPLab1/scripts/ScriptMediciones.py) en python que toma las mediciones realizadas del circuito y nos facilita las lecturas de los valores siguientes

In [1]:
import pandas as pd

datos = {
    "Caso 1: Rs = 10, Rf = 1k": [
        [10,    0.100984,  -1.00984e-05],
        [100,   0.100459,  -1.00459e-05],
        [1000,  0.095202,  -9.5202e-06],
        [10000, 0.0426354, -4.26354e-06],
        [100000,-0.482941,   4.82941e-05],
    ],
    
    "Caso 2: Rs = 100, Rf = 10k": [
        [10,    0.101908,  -1.01908e-05],
        [100,   0.101383,  -1.01383e-05],
        [1000,  0.096126,  -9.61256e-06],
        [10000, 0.0435552, -4.35552e-06],
        [100000,-0.482056,   4.82056e-05],
    ],
    
    "Caso 3: Rs = 1k, Rf = 100k": [
        [10,    0.111072,  -1.11072e-05],
        [100,   0.110546,  -1.10546e-05],
        [1000,  0.105289,  -1.05289e-05],
        [10000, 0.0527181, -5.27181e-06],
        [100000,-0.472899,   4.72899e-05],
    ],
    
    "Caso 4: Rs = 10k, Rf = 1Meg": [
        [10,    0.202696,  -2.02696e-05],
        [100,   0.202171,  -2.02171e-05],
        [1000,  0.196913,  -1.96913e-05],
        [10000, 0.144342,  -1.44342e-05],
        [100000,-0.381283,   3.81283e-05],
    ]
}

for titulo, valores in datos.items():
    df = pd.DataFrame(valores, columns=["R", "VOUT", "IRL"])
    
    print(f"\n{titulo} (R variable)")
    display(df)

Caso 1: Rs = 10, Rf = 1k (R variable)

        R      VOUT       IRL
0      10  0.100984 -0.000010
1     100  0.100459 -0.000010
2    1000  0.095202 -0.000010
3   10000  0.042635 -0.000004
4  100000 -0.482941  0.000048

Caso 2: Rs = 100, Rf = 10k (R variable)

        R      VOUT       IRL
0      10  0.101908 -0.000010
1     100  0.101383 -0.000010
2    1000  0.096126 -0.000010
3   10000  0.043555 -0.000004
4  100000 -0.482056  0.000048

Caso 3: Rs = 1k, Rf = 100k (R variable)

        R      VOUT       IRL
0      10  0.111072 -0.000011
1     100  0.110546 -0.000011
2    1000  0.105289 -0.000011
3   10000  0.052718 -0.000005
4  100000 -0.472899  0.000047

Caso 4: Rs = 10k, Rf = 1Meg (R variable)

        R      VOUT       IRL
0      10  0.202696 -0.000020
1     100  0.202171 -0.000020
2    1000  0.196913 -0.000020
3   10000  0.144342 -0.000014
4  100000 -0.381283  0.000038

-  Realizando un análisis circuital, en el cual el nodo $V_{in}=0$ de la *Ilustración 2*, será denominado nodo $V_x$, determinamos una corriente que circula desde $V_{out}$ hacia $V_x$ a través de $R_f$, denominada $I$. Esta corriente se divide en dos componentes: una corriente $I_{R_s}$, que circula a través de $R_s$, y una pequeña corriente $I_{B1}$, correspondiente a la corriente de polarización que ingresa al terminal inversor del amplificador operacional. Asimismo, se considera la corriente de polarización $I_{B2}$, que ingresa al terminal no inversor, cuyo potencial es también $V_x$.

Por lo tanto, aplicando la Ley de Corrientes de Kirchhoff (LCK) en el nodo $V_x$, se obtiene:

$$
V_x = -I_{B2}\cdot R \\
$$
$$
I_{Rs} = \frac{V_x}{Rs}$$
$$
I = I_{R_s} + I_{B1} = \frac{V_{out}-V_x}{Rf}
$$
Operando un poco algebraicamente llegamos a
$$
\frac{V_{out}}{Rf} = V_x\left( \frac{1}{Rs} + \frac{1}{Rf}\right) + I_{B1}
$$
Si consideramos el caso en donde  $\left(\frac{1}{Rs} + \frac{1}{Rf}^{-1}\right) \approx R$, nos permite tener una diferencia de corrientes mucho menor en ambas entradas
$$
\frac{V_{out}}{Rf} = -I_{B2} + I_{B1} = I_{io}
$$
Y terminamos obteniendo lo que se denomina *tension de salida residual*

$$
\boxed{
V_{out}= I_{io} \cdot Rf}
$$

Teniendo esto en consideracion nos facilita el porqué de nuestros resultados.

<div align="center">
  <img src="imagenes/1/ilustracion3.png" width="600">
  <figcaption>Ilustración 3 Grafica de los resultados.</figcaption>
</div>

 -   Como podemos observar, al mantener constante la relación $Rf/Rs$ en todos los casos, podemos analizar la influencia de la resistencia R sobre la corriente de salida. Para valores pequeños de R, la magnitud de la corriente de salida es relativamente elevada. A medida que R aumenta, la magnitud de dicha corriente disminuye hasta aproximarse a cero, y para valores mayores de R la corriente cambia de signo y vuelve a aumentar en magnitud.
    Este comportamiento se relaciona con la corriente de polarización de la entrada no inversora, ya que al aumentar R aumenta la caida de tension $Vz=−IB2R$, modificando las corrientes de polarizacion al offset de salida. Sabemos que $R=R//Rf$ permite igualar aproximadamente las resistencias vistas por ambas entradas y minimizar el efecto asociado a las corrientes de polarización. Sin embargo, el mínimo de la corriente de salida total observado en la simulacion nos coincide con este valor, puede que sea debido a que intervienen otros parametros del modelo del amplificador operacional, como la tension de offset de entrada.

- Como mencionamos anteriormente la reitencia $R$ permite poder igualar las resitencias vistas por ambas entradas del operacional, y minimizar la tension de sali residual, con $R = 0$ nos termina quedando la siguiente expresion:

$$
Vort = Vio (1 + \frac{R2}{R1}) + I_B\cdot Rs
$$

En donde $I_B \cdot Rs$ puede llegar a ser considerablemente mayor a los casos que analizamos, por lo tanto no poner la resistencia $R$ viene acompañado de un considerado mayor error de offset.

- Realizamos el circuito para el operacional LT1012
<div align="center">
  <img src="imagenes/1/ilustracion4.png" width="600">
  <figcaption>Ilustración 4 .</figcaption>
</div>
    Obtenemos la siguiente salida
<div align="center">
  <img src="imagenes/1/ilustracion5.png" width="500">
  <figcaption>Ilustración 5 Salida del LT1012.</figcaption>
</div>


<div align="center">
  <img src="imagenes/1/ilustracion6.png" width="500">
  <figcaption>Ilustración 6 Salida del LM741.</figcaption>
</div>

Como pode